version:0.2
phases:
  pre-build:
    commands:
      -echo "Entered into pre-build phsase"
  build:
    commands:
      -echo "Building the project"
      -mvn clean prepare-package war:exploded
  post-build:
    commands:
      -echo "Entered into post-build phase"
      -mv target/deploy ./
artifacts:
  files:
    -deploy/**/*
